receivers:
  glean:
    endpoint: localhost:8888
    path: /submit/telemetry
    read_header_timeout: 20s

exporters:
  logging:
    loglevel: debug

service:
  pipelines:
    metrics:
      receivers: [glean]
      exporters: [logging]
    logs:
      receivers: [glean]
      exporters: [logging]
